### PR TITLE
adding overlay search bar

### PR DESCRIPTION
**Pull request by muhamad3**

### CODE REVIEW

**Comment by Yassin-H-Rassul** [comment]
Bram awa atu har xareke push krdn u dastkare krdne ka esta 2024'a?

**Comment by muhamad3** [comment]
nawala bram awa har vs codeka pishany aya bardawam bezary krdbum buya wtm
ba yakjary pushykam w namene

**Comment by Yassin-H-Rassul** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by muhamad3** [comment]
bram esta la asiacell dawam akam w dway dawmish har lagal flutter xarikm ,
ay ewa xariki chin esta lakwen


facebook:
https://www.facebook.com/muhamadtahsin0?mibextid=kFxxJD


linkedin:
https://www.linkedin.com/in/muhamad-tahsin-29b80a1a9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app



whatsapp w viber telegramish har lasar am raqamaya

07701180648

**Comment by Yassin-H-Rassul** [comment]
Bragyan wa add u shtm bo narde, lawe jwabt adamawa

**Pull request closed without merging**
